import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Contacto y soporte técnico', description: 'Contacta a Next IP en El Salvador para consultar cobertura, resolver dudas sobre internet de fibra óptica y recibir soporte técnico.', alternates: { canonical: '/contacto' }, openGraph: { title: 'Contacto y soporte técnico | Next IP', description: 'Consulta cobertura y contacta al equipo de Next IP en El Salvador.', type: 'website', locale: 'es_SV', url: '/contacto', siteName: 'Next IP Network', images: [{ url: '/images/wifi-connection.jpg', alt: 'Conexión WiFi para el hogar' }] }, twitter: { card: 'summary_large_image', title: 'Contacto y soporte técnico | Next IP', description: 'Consulta cobertura y contacta al equipo de Next IP.', images: ['/images/wifi-connection.jpg'] } }
import { ArrowRight } from 'lucide-react'
import { ContactForm, FAQ } from '@/components/interactive'
import { ContactIcon, PageShell } from '@/components/site-shell'
const faqs = [{ question: '¿Cómo puedo saber si hay cobertura en mi dirección?', answer: 'Puedes consultarla escribiéndonos. Revisaremos tu zona y te diremos qué opciones están disponibles.' }, { question: '¿Cómo contacto con soporte técnico?', answer: 'Escríbenos a hola@nextip.network o cuéntanos qué necesitas en el formulario. Nuestro equipo está disponible las 24 horas, todos los días.' }, { question: '¿Dónde puedo consultar el estado de la red?', answer: 'En esta página encontrarás información actualizada sobre el estado de la red en tu zona.' }, { question: '¿Cómo actualizo mis datos personales?', answer: 'Puedes solicitar la actualización de tus datos desde el formulario de contacto.' }, { question: '¿Ofrecen atención para empresas?', answer: 'Sí. Contamos con un equipo especializado en soluciones de conectividad para empresas de todos los tamaños.' }]
const contact = [{ type: 'mail' as const, label: 'Escríbenos', value: 'hola@nextip.network', href: 'mailto:hola@nextip.network' }, { type: 'phone' as const, label: 'Llámanos', value: '0000-0000', href: 'tel:+50300000000' }, { type: 'map' as const, label: 'Ubicación', value: 'San Salvador, El Salvador', href: 'https://www.google.com/maps/search/?api=1&query=San+Salvador%2C+El+Salvador' }]
export default async function Contact({ searchParams }: { searchParams: Promise<{ plan?: string | string[] }> }) {
	const { plan } = await searchParams
	const selectedPlan = typeof plan === 'string' && ['esencial', 'conecta', 'ultra'].includes(plan) ? plan : ''

	return <PageShell active="contacto"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }) }} /><main><section className="page-hero"><div className="container narrow"><span className="eyebrow">ESTAMOS PARA AYUDARTE</span><h1>Hablemos de<br /><span>lo que necesitas.</span></h1><p>Una pregunta, una incidencia o una idea. Cuéntanoslo y te responderemos con claridad.</p></div></section><section className="section contact-section"><div className="container contact-grid"><div><span className="eyebrow dark">ESCRÍBENOS</span><h2>Estamos al otro<br /><em>lado.</em></h2><p className="contact-intro">Completa el formulario y una persona de nuestro equipo se pondrá en contacto contigo.</p><ContactForm initialPlan={selectedPlan} /></div><aside className="contact-aside"><div className="aside-card"><span className="eyebrow dark">CONTACTO DIRECTO</span>{contact.map(item => <a className="contact-method" href={item.href} key={item.label}><span className="contact-icon"><ContactIcon type={item.type} /></span><span><small>{item.label}</small><strong>{item.value}</strong></span><ArrowRight size={16} /></a>)}<div className="aside-note"><strong>Horario de atención</strong><p>Soporte técnico disponible las 24 horas, todos los días del año.</p></div></div></aside></div></section><section className="section section-light" id="faq"><div className="container faq-layout general-faq"><div><span className="eyebrow dark">ANTES DE ESCRIBIR</span><h2>Preguntas<br /><em>frecuentes.</em></h2><p>Las respuestas más rápidas a las dudas más habituales.</p></div><FAQ items={faqs} /></div></section></main></PageShell>
}
