import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Planes de internet de fibra óptica', description: 'Compara planes de fibra óptica simétrica de 300 Mb, 600 Mb y 1 Gb desde $29,90 al mes. Elige tu velocidad, sin permanencia.', alternates: { canonical: '/planes' }, openGraph: { title: 'Planes de internet de fibra óptica | Next IP', description: 'Compara planes de fibra óptica simétrica de 300 Mb, 600 Mb y 1 Gb desde $29,90 al mes.', type: 'website', locale: 'es_SV', url: '/planes', siteName: 'Next IP Network', images: [{ url: '/images/connection-workspace.png', alt: 'Personas colaborando con tecnología en un entorno de trabajo' }] }, twitter: { card: 'summary_large_image', title: 'Planes de fibra óptica | Next IP', description: 'Compara velocidades y precios de internet de fibra óptica simétrica.', images: ['/images/connection-workspace.png'] } }
import { ArrowRight, Check } from 'lucide-react'
import { FAQ } from '@/components/interactive'
import { CheckItem, PageShell } from '@/components/site-shell'
import { PlanPrice, PricingPeriod } from '@/components/pricing'

const faqs = [{ question: '¿Puedo cambiar de plan más adelante?', answer: 'Sí. Puedes cambiar de plan cuando quieras desde el área personal o contactando a nuestro equipo.' }, { question: '¿La instalación tiene costo adicional?', answer: 'La instalación está incluida en nuestros planes de fibra óptica.' }, { question: '¿Hay contrato de permanencia?', answer: 'No. Nuestros planes no tienen permanencia; puedes cancelar el servicio cuando quieras.' }]
const plans = [{ id: 'esencial', name: 'Esencial', speed: '300 Mb', price: '29,90', description: 'Todo lo necesario para navegar, trabajar y disfrutar.', benefits: ['Fibra óptica simétrica', 'Router WiFi 6 incluido', 'Línea fija nacional'], color: '' }, { id: 'conecta', name: 'Conecta', speed: '600 Mb', price: '39,90', description: 'Más velocidad para hogares conectados y creativos.', benefits: ['Fibra óptica simétrica', 'Router WiFi 6 incluido', 'Línea fija nacional', 'Soporte prioritario'], color: 'featured' }, { id: 'ultra', name: 'Ultra', speed: '1 Gb', price: '49,90', description: 'La máxima potencia para no parar nunca.', benefits: ['Fibra óptica simétrica', 'Router WiFi 6 incluido', 'Línea fija nacional', 'Soporte prioritario', 'IP fija incluida'], color: '' }]
export default function Plans() { return <PageShell active="planes"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }) }} /><main><section className="page-hero"><div className="container narrow"><span className="eyebrow">PLANES NEXT IP</span><h1>Más velocidad.<br /><span>Menos vueltas.</span></h1><p>Elige la conexión que encaja contigo. Transparente, flexible y sin permanencia.</p></div></section><section className="section section-light"><div className="container"><PricingPeriod><div className="plans-detail-grid">{plans.map(plan => <article className={`detail-plan ${plan.color}`} key={plan.id}>{plan.color && <span className="popular-badge">MÁS POPULAR</span>}<span className="plan-name">{plan.name}</span><h2>{plan.speed}</h2><p className="plan-description">{plan.description}</p><PlanPrice basePrice={Number(plan.price.replace(',', '.'))} /><ul>{plan.benefits.map(benefit => <CheckItem key={benefit}>{benefit}</CheckItem>)}</ul><Link className={plan.color ? 'button button-primary full-width' : 'button button-outline full-width'} href={`/contacto?plan=${plan.id}#formulario`}>Lo quiero <ArrowRight size={15} /></Link></article>)}</div></PricingPeriod></div></section><section className="section faq-section"><div className="container faq-layout"><div><span className="eyebrow dark">RESOLVEMOS TUS DUDAS</span><h2>Preguntas sobre<br /><em>los planes.</em></h2><p>Si no encuentras lo que buscas, nuestro equipo está a un mensaje de distancia.</p><Link className="text-link" href="/contacto">Hablar con soporte <ArrowRight size={16} /></Link></div><FAQ items={faqs} /></div></section><section className="final-cta compact"><div className="container cta-inner"><div><span className="eyebrow">¿LO TIENES CLARO?</span><h2>Conecta con<br /><span>lo que importa.</span></h2></div><Link className="button button-primary" href="/contacto">Empezar ahora <ArrowRight size={17} /></Link></div></section></main></PageShell> }
